title = "xbo1 Blog"
baseURL = "http://blog.xbo1.com"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "zh"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = ""

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "xbo1"
  description = "xbo1 blog."
  keywords = "blog,personal"

  # How many articles should be displayed at once?
  paginate = 7

  # Enable / Disable MathJax
  enable_mathjax    = true

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "NG7XI64K3K"
  algolia_apiKey    = "dfde7326483659bf901cdb718346ebc7"
  algolia_indexName = "xbo1"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "you are what you choose."

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = ""

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = false
    link = "http://blog.xbo1.com"

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = ""
  googleplus = ""
  pinterest  = ""
  instagram  = ""
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/xbo1"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
